server:
  port: 9091

spring:
  datasource:
    url: 'jdbc:sqlserver://localhost;databaseName=db_test;encrypt=true;trustServerCertificate=true'
    username: 'updateThis'
    password: 'updateThis'
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    open-in-view: false
  jpa:
    show-sql: false
    #    database-platform: org.hibernate.dialect.SQLServerDialect
    generate-ddl: false
    open-in-view: false
  application:
    name: customer-service
management:
  tracing:
    sampling:
      probability: 1.0
    baggage:
      correlation:
        enabled: true
        fields: trace_id,caller_context_id,context_id,biz_func,message_type,biz_keys,marker
      remote-fields: x-user-id,Authorization,x-AIAHK-Trace-ID,x-AIAHK-Context-ID,x-aia-lbu,x-aia-env,X-Gateway-APIKey,x-forwarded-for
  endpoints:
    enabled-by-default: false

custom:
  baggage:
    correlation-fields: ${management.tracing.baggage.correlation.fields}
    remote-fields: ${management.tracing.baggage.remote-fields}
    correlation-fields-alias:
      x-AIAHK-Trace-ID: trace_id
      x-AIAHK-Context-ID: caller_context_id


logging:
  pattern:
    console: "[%d{yyyy-MM-dd'T'HH:mm:ss.SSSZ}]%clr([${LOG_LEVEL_PATTERN:%0.5p}])[%0.50logger{39}][%clr(%0.-10X{trace_id})][%0.-10X{context_id}][%0.-50X{caller_context_id}][%0.-20X{app_id}][%0.-30X{biz_func}][%marker][%0.-10X{app_version}][%0.-20t][%0.-250X{biz_keys}] %clr(%0.-250m%n)"


customer:
  greeting:
    url: http://localhost:9091